# http://127.0.0.1:8001/api/v1/namespaces/default/pods/
# http://127.0.0.1:8001/api/v1/namespaces/default/pods/nginx-alone/proxy/

apiVersion: v1
kind: Pod
metadata:
  name: nginx-alone
spec:
  containers:
    - name: nginx-alone
      image: nginx:1.16.0-alpine
      ports:
        - containerPort: 80
