apiVersion: v1
kind: Service
metadata:
  name: nginx-service-another
spec:
  selector:
    app: nginx-test
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo-another
  labels:
    app: nginx-test
spec:
  containers:
    - name: nginx-demo-another
      image: nginx
      ports:
        - containerPort: 80
